- name: Raphson
  hosts: all
  tasks:
    - name: Notify
      ansible.builtin.shell:
        cmd: "notify-send --app-name Ansible 'Systeem wordt bijgewerkt'"

    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - firefox
          - libreoffice
          - mpv
          - okular
          - keepassxc
          - filezilla
          - minetest
          - openscad
          - kate
          - torbrowser-launcher
          - htop
          - screen
          - prusa-slicer
          - gnome-mines
          - gnome-mahjongg
          - gnome-robots
        state: present

    - name: Add Flathub
      become: true
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Remove Fedora Flatpaks
      become: true
      community.general.flatpak_remote:
        name: fedora
        state: absent

    - name: Install Flatpak packages
      become: true
      community.general.flatpak:
        name:
          - org.freecadweb.FreeCAD
          - org.openstreetmap.josm
          - com.github.qarmin.czkawka
          - org.nicotine_plus.Nicotine

    - name: Set wallpaper
      community.general.kdeconfig:
        path: /home/raphson/.config/plasma-org.kde.plasma.desktop-appletsrc
        values:
          - groups: ['Containments', '1']
            key: wallpaperplugin
            value: 'org.kde.image'
          - groups: ['Containments', '1', 'Wallpaper', 'org.kde.image', 'General']
            key: Image
            value: /home/raphson/Pictures/bg.png

    - name: Mount /mnt/share
      become: true
      ansible.posix.mount:
        src: 10.131.12.2:/snel/share
        path: /mnt/share
        state: present
        fstype: nfs

    - name: Mount directories in home
      become: true
      ansible.posix.mount:
        src: 10.131.12.2:/snel/share/{{ item }}
        path: /home/raphson/{{item}}
        state: present
        fstype: nfs
      loop: [Documents, Downloads, Pictures, Desktop, Videos, Music, Arduino]
