- name: Raphson
  hosts: all
  tasks:
    - name: Notify
      ansible.builtin.shell:
        cmd: "notify-send --app-name 'Hokkie Ansible' 'Systeem wordt bijgewerkt'"

    - name: Install rpmfusion
      become: yes
      ansible.builtin.dnf:
        name:
          - 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm'
          - 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm'
        state: present

    - name: Replace ffmpeg-free with ffmpeg
      become: yes
      ansible.builtin.dnf:
        name: ffmpeg
        allowerasing: true

    - name: Enable H264 repository
      become: yes
      community.general.dnf_config_manager:
        name: fedora-cisco-openh264
        state: enabled

    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - firefox
          - libreoffice
          - mpv
          - okular
          - keepassxc
          - filezilla
          - minetest
          - openscad
          - kate
          - torbrowser-launcher
          - htop
          - screen
          - prusa-slicer
          - gnome-mines
          - gnome-mahjongg
          - gnome-robots
          - qview
        state: present

    - name: Add Flathub
      become: true
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Remove Fedora Flatpaks
      become: true
      community.general.flatpak_remote:
        name: fedora
        state: absent

    - name: Install Flatpak packages
      become: true
      community.general.flatpak:
        name:
          - org.freecadweb.FreeCAD
          - org.openstreetmap.josm
          - com.github.qarmin.czkawka
          - org.nicotine_plus.Nicotine

    # https://github.com/shalva97/kde-configuration-files
    - name: Set wallpaper
      community.general.kdeconfig:
        path: /home/raphson/.config/plasma-org.kde.plasma.desktop-appletsrc
        values:
          - groups: ['Containments', '1']
            key: wallpaperplugin
            value: 'org.kde.image'
          - groups: ['Containments', '1', 'Wallpaper', 'org.kde.image', 'General']
            key: Image
            value: /home/raphson/Pictures/bg.png

    - name: Enable automatic updates
      community.general.kdeconfig:
        path: /home/raphson/.config/PlasmaDiscoverUpdates
        values:
          - groups: ['Global']
            key: UseUnattendedUpdates
            value: 'true'

    - name: Configure Dolphin
      community.general.kdeconfig:
        path: /home/raphson/.config/dolphinrc
        values:
          - groups: ['General']
            key: ConfirmClosingMultipleTabs
            value: 'false'
          - groups: ['General']
            key: RememberOpenedTabs
            value: 'false'
          - groups: ['General']
            key: ShowFullPath
            value: 'true'
          - groups: ['General']
            key: ShowFullPathInTitlebar
            value: 'true'

    - name: Hide 'Remote' section in Dolphin
      community.general.xml:
        path: /home/raphson/.local/share/user-places.xbel
        xpath: /xbel/info/metadata/GroupState-Remote-IsHidden
        value: 'true'

    - name: Enable thumbnails for remote folders
      community.general.kdeconfig:
        path: /home/raphson/.config/kdeglobals
        values:
          - groups: ['PreviewSettings']
            key: MaximumRemoteSize
            value: '1073741824' # 1 GiB
          - groups: ['PreviewSettings']
            key: EnableRemoteFolderThumbnail
            value: 'true'

    - name: Configure power saving
      community.general.kdeconfig:
        path: /home/raphson/.config/powerdevilrc
        values:
          - groups: ['AC', 'Display']
            key: DimDisplayWhenIdle
            value: 'false'
          - groups: ['AC', 'Display']
            key: TurnOffDisplayIdleTimeoutSec
            value: 3600
          - groups: ['AC', 'SuspendAndShutdown']
            key: PowerButtonAction
            value: 8 # shut down

    - name: Mount /mnt/share
      become: true
      ansible.posix.mount:
        src: 10.131.12.2:/snel/share
        path: /mnt/share
        state: mounted
        fstype: nfs

    - name: Mount directories in home
      become: true
      ansible.posix.mount:
        src: 10.131.12.2:/snel/share/{{ item }}
        path: /home/raphson/{{item}}
        state: mounted
        fstype: nfs
      loop: [Documents, Downloads, Pictures, Desktop, Videos, Music, Arduino]
