- name: Raphson
  hosts: all
  tasks:
    - name: Notify
      ansible.builtin.shell:
        cmd: "notify-send --app-name 'Hokkie Ansible' 'Systeem wordt bijgewerkt'"
      changed_when: False

      # F41 bug, python3-libdnf5 is not a dependency of ansible and must be manually installed first
    - name: Manually install libdnf5
      become: true
      ansible.builtin.shell:
        cmd: dnf --assumeyes install python3-libdnf5

    - name: Install SSH keys
      ansible.builtin.copy:
        src: authorized_keys
        dest: /home/raphson/.ssh/authorized_keys

    - name: Set hostname
      become: true
      ansible.builtin.copy:
        content: '{{ inventory_hostname }}'
        dest: /etc/hostname

    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - firefox
          - libreoffice
          - mpv
          - okular
          - keepassxc
          - filezilla
          - minetest
          - openscad
          - kate
          - torbrowser-launcher
          - htop
          - screen
          - prusa-slicer
          - gnome-mines
          - gnome-mahjongg
          - gnome-robots
          - qview
          - kde-connect
          - thunderbird
          - cura
        state: present

    - name: rpmfusion
      ansible.builtin.include_tasks:
        file: tasks/rpmfusion.yaml

    - name: kde
      ansible.builtin.include_tasks:
        file: tasks/kde.yaml

    - name: nfs
      ansible.builtin.include_tasks:
        file: tasks/nfs.yaml

    - name: vscode
      ansible.builtin.include_tasks:
        file: tasks/vscode.yaml

    - name: boot splash screen
      ansible.builtin.include_tasks:
        file: tasks/plymouth.yaml

    - name: Add Flathub
      become: true
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Remove Fedora Flatpaks
      become: true
      community.general.flatpak_remote:
        name: fedora
        state: absent

    - name: Install Flatpak packages
      become: true
      community.general.flatpak:
        name:
          - org.freecadweb.FreeCAD
          - org.openstreetmap.josm
          - com.github.qarmin.czkawka
          - org.nicotine_plus.Nicotine

    # - name: Enable mpv hardware decoding
    #   ansible.builtin.copy:
    #     content: 'hwdec=auto'
    #     dest: '/home/raphson/.config/mpv/mpv.conf'

    - name: Notify
      ansible.builtin.shell:
        cmd: "notify-send --app-name 'Hokkie Ansible' 'Klaar'"
      changed_when: False
