---
- name: Install Microsoft key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Microsoft repository
  become: true
  ansible.builtin.copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo

- name: Install package
  become: true
  ansible.builtin.package:
    name: code
    state: present
