- name: Raphson
  hosts: desktops

  tasks:
    - name: Notify
      shell:
        cmd: "notify-send --app-name 'Hokkie Ansible' 'Systeem wordt bijgewerkt'"
      changed_when: False

      # In Fedora 41 python3-libdnf5 must be manually installed first
    - name: Install libdnf5
      become: true
      shell:
        cmd: dnf --assumeyes install python3-libdnf5

    - name: rpmfusion
      include_role:
        name: ../roles/rpmfusion

    - name: Apply base configuration
      include_role:
        name: ../roles/base

    - name: Install packages
      become: true
      package:
        name:
          - firefox
          - libreoffice
          - mpv
          - okular
          - keepassxc
          - filezilla
          - minetest
          - openscad
          - kate
          - torbrowser-launcher
          - screen
          - prusa-slicer
          - gnome-mines
          - gnome-mahjongg
          - gnome-robots
          - qview
          - kde-connect
          - thunderbird
          - cura
        state: present

    - name: kde
      include_tasks:
        file: ../tasks/kde.yaml

    - name: ceph
      include_role:
        name: ../roles/ceph-desktops

    - name: vscode
      include_role:
        name: ../roles/vscode

    - name: boot splash screen
      include_role:
        name: ../roles/raphson-boot
      when: inventory_hostname != "kledertv"

    - name: Add Flathub
      become: true
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Remove Fedora Flatpaks
      become: true
      community.general.flatpak_remote:
        name: fedora
        state: absent

    - name: Install Flatpak packages
      become: true
      community.general.flatpak:
        name:
          - org.freecadweb.FreeCAD
          - org.openstreetmap.josm
          - com.github.qarmin.czkawka
          - org.nicotine_plus.Nicotine

    - name: Download Snap4Arduino
      get_url:
        url: 'https://downloads.rkslot.nl/software/snap4arduino.flatpak'
        dest: /tmp/snap4arduino.flatpak

    - name: Install Snap for Arduino
      become: true
      shell:
        cmd: flatpak install -y /tmp/snap4arduino.flatpak || true

    # - name: Enable mpv hardware decoding
    #   copy:
    #     content: 'hwdec=auto'
    #     dest: '/home/raphson/.config/mpv/mpv.conf'

    - name: Notify
      shell:
        cmd: "notify-send --app-name 'Hokkie Ansible' 'Klaar'"
      changed_when: False
