- name: Raphson
  hosts: desktops

  pre_tasks:
    - name: Notify
      ansible.builtin.command:
        cmd: "notify-send --app-name 'Hokkie Ansible' 'Systeem wordt bijgewerkt'"
      changed_when: false

      # In Fedora 41 python3-libdnf5 must be manually installed first
      # is als het goed is niet meer nodig
    # - name: Install libdnf5
    #   become: true
    #   ansible.builtin.command:
    #     cmd: dnf --assumeyes install python3-libdnf5

  post_tasks:
    - name: Notify finished
      ansible.builtin.command:
        cmd: "notify-send --app-name 'Hokkie Ansible' 'Klaar'"
      changed_when: false

  roles:
    - base
    - ssh
    - update
    - rpmfusion
    - mpv
    - desktops-nfs
    - desktops-kde
    - vscode
    - flathub
    - snap4arduino

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - firefox
          - libreoffice
          - okular
          - keepassxc
          - filezilla
          - minetest
          - openscad
          - kate
          - krename
          - filelight
          - torbrowser-launcher
          - screen
          - prusa-slicer
          - gnome-mines
          - gnome-mahjongg
          - gnome-robots
          - qview
          - kde-connect
          - thunderbird
          - cura
          - distrobox
          - pdfmerge
        state: present

    - name: Boot splash screen
      ansible.builtin.include_role:
        name: raphson-boot
      when: inventory_hostname != "kledertv"

    - name: Install Flatpak packages
      become: true
      community.general.flatpak:
        name:
          - org.freecadweb.FreeCAD
          - org.openstreetmap.josm
          - com.github.qarmin.czkawka
          - org.nicotine_plus.Nicotine
