- name: Specs
  hosts: desktops
  tasks:
    - name: install required packages
      become: true
      package:
        name:
         - colorized-logs
         - fastfetch

    - name: fastfetch
      shell:
        cmd: "fastfetch --logo none | ansi2txt"
      register: fetch

    - name: print
      lineinfile:
        dest: specs.txt
        line: "{{ fetch.stdout }}"
        create: true
      delegate_to: localhost
