---
- name: Install packages
  ansible.posix.package:
    name: ceph-common

- name: Install configuration
  become: true
  ansible.posix.copy:
    src: ceph.conf
    dest: /etc/ceph/ceph.conf

- name: Install keyring
  become: true
  ansible.posix.copy:
    src: ceph.client.desktops.keyring
    dest: /etc/ceph/client.desktops.keyring

- name: Mount /mnt/share
  become: true
  ansible.posix.mount:
    src: :/desktops
    path: /mnt/share
    state: mounted
    fstype: ceph
    opts: name=desktops

- name: Mount directories in home
  become: true
  ansible.posix.mount:
    src: ':/desktops/{{ item }}'
    path: '/home/raphson/{{ item }}'
    state: mounted
    fstype: ceph
    opts: name=desktops
  loop: [Documents, Downloads, Pictures, Desktop, Videos, Music, Arduino]
