---
- name: Install base packages
  become: true
  ansible.builtin.package:
    name:
      - htop
      - ncdu
      - tmux
      - screen
      - rsync

- name: Set hostname
  become: true
  ansible.builtin.copy:
    content: '{{ inventory_hostname }}'
    dest: /etc/hostname
    mode: '644'

- name: Install aliases file
  ansible.builtin.copy:
    src: aliases
    dest: .local/share/aliases
    mode: '644'

- name: Source aliases in .bashrc
  ansible.builtin.lineinfile:
    line: source ~/.local/share/aliases
    path: .bashrc
