---

- name: Install SSH keys
  copy:
    src: authorized_keys
    dest: .ssh/authorized_keys

- name: Install base packages
  package:
    name:
      - 'htop'

- name: Set hostname
  become: true
  copy:
    content: '{{ inventory_hostname }}'
    dest: /etc/hostname
